name: disaster_app
description: A comprehensive Disaster Management Mobile App built with Flutter.

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
    
  # UI & Navigation
  google_fonts: ^6.2.0
  animations: ^2.0.11
  flutter_riverpod: ^2.6.1
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  cupertino_icons: ^1.0.2

  # Firebase
  firebase_core: ^3.1.0
  firebase_auth: ^5.6.0
  cloud_firestore: ^5.5.0
  firebase_messaging: ^15.0.0
  firebase_storage: ^12.0.0
  cloud_functions: ^5.0.0

  # Data & Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  sqflite: ^2.3.0
  sqflite_common_ffi_web: ^0.4.2+4
  path: ^1.8.3
  http: ^1.3.1

  # Maps & Location
  google_maps_flutter: ^2.6.1
  geolocator: ^12.0.0
  geocoding: ^3.0.0

  # Media & Files
  image_picker: ^1.0.7
  camera: ^0.10.5+9
  video_player: ^2.8.2

  # Utilities
  intl: ^0.19.0
  url_launcher: ^6.2.4
  permission_handler: ^11.3.0
  connectivity_plus: ^5.0.2
  shared_preferences: ^2.2.2
  flutter_local_notifications: ^19.4.0

  # UI Components
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0
  lottie: ^3.0.0

dev_dependencies:
  build_runner: ^2.4.7
  freezed: ^2.4.7
  json_serializable: ^6.8.0
  hive_generator: ^2.0.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/

