name: disaster_app
description: A new Flutter project.

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
    

  # pubspec.yaml  (add to your existing list)

    


  # UI
  google_fonts: ^6.2.0
  animations: ^2.0.11
  flutter_riverpod: ^2.6.1
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0

  # Firebase
  firebase_core: ^3.1.0
  firebase_auth: ^5.6.0
  cloud_firestore: ^5.5.0
  firebase_messaging: ^15.0.0

  # Data / platform
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^1.3.1
  google_maps_flutter: ^2.6.1
  geolocator: ^12.0.0

dev_dependencies:
  build_runner: ^2.4.7
  freezed: ^2.4.7
  json_serializable: ^6.8.0
  flutter_test:
    sdk: flutter

