// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNhY-aLzJDradETaC9UMThWKsfpNZJXIw',
    appId: '1:90483820606:web:88deda3ff5fab146b5296f',
    messagingSenderId: '90483820606',
    projectId: 'disaster-management-a5f61',
    authDomain: 'disaster-management-a5f61.firebaseapp.com',
    storageBucket: 'disaster-management-a5f61.firebasestorage.app',
    measurementId: 'G-F6EGWQG242',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBeEBfDe4ubZsw-VrM7lOsqv0zCWiIvcGE',
    appId: '1:90483820606:android:55aa6cb946fa15bbb5296f',
    messagingSenderId: '90483820606',
    projectId: 'disaster-management-a5f61',
    storageBucket: 'disaster-management-a5f61.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTKnMMz3nuZ7JUayJpUTX_ma6Ai2VRaeI',
    appId: '1:90483820606:ios:e6384ea21c40688fb5296f',
    messagingSenderId: '90483820606',
    projectId: 'disaster-management-a5f61',
    storageBucket: 'disaster-management-a5f61.firebasestorage.app',
    iosBundleId: 'com.example.disasterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTKnMMz3nuZ7JUayJpUTX_ma6Ai2VRaeI',
    appId: '1:90483820606:ios:e6384ea21c40688fb5296f',
    messagingSenderId: '90483820606',
    projectId: 'disaster-management-a5f61',
    storageBucket: 'disaster-management-a5f61.firebasestorage.app',
    iosBundleId: 'com.example.disasterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCNhY-aLzJDradETaC9UMThWKsfpNZJXIw',
    appId: '1:90483820606:web:bd64b5f64ea117d3b5296f',
    messagingSenderId: '90483820606',
    projectId: 'disaster-management-a5f61',
    authDomain: 'disaster-management-a5f61.firebaseapp.com',
    storageBucket: 'disaster-management-a5f61.firebasestorage.app',
    measurementId: 'G-FN57F9JSP1',
  );
}
